#PBS -N cs6210-proj2_combined_p2t2
#PBS -l nodes=1:ppn=2+1:ppn=2
#PBS -l pmem=1gb
#PBS -l walltime=00:30:00
#PBS -q coc-ice
#PBS -j oe
#PBS -o combined_p2_t2.out
echo 'Started on `/bin/hostname`'
echo 'Nodes chosen are:'

export VIADEV_USE_AFFINITY=0
export MV2_ENABLE_AFFINITY=0
export OMP_PROC_BIND=true
export MPV_CPU_BINDING_POLICY=hybrid

cd ~/cs6210/p2/combined
module load gcc mvapich2/2.3
export OMP_NUM_THREADS=2
make clean all
cat $PBS_NODEFILE | uniq > hostfile
mpirun -np 2 -hostfile hostfile ./combined 2

