#PBS -N mpi-example-8p.pbs
#PBS -o mpi-example-8p-log.out
#PBS -l nodes=1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1+1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=00:05:00
#PBS -q coc-ice
#PBS -j oe

export MPI_NUM_PROCS=8

mkdir -p ~/tmp/mpi-example-8p/
cp ~/cs6210/p2/mpi/* ~/tmp/mpi-example-8p/
cd ~/tmp/mpi-example-8p/
module load gcc/8.3.0/ intel/19.0.5 mvapich2/2.3.2
make clean baseline

mpirun -np 8 ./baseline 8
rm -rf ~/tmp/mpi-example-8p/
